# Generated by Django 5.1.15 on 2026-05-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
